version: "3.9"

services:
  db:
    image: mysql:8.0.31
    cpus: 1.5
    mem_limit: 2048m
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@Teoola_project
      MYSQL_DATABASE: teoola_translations
      MYSQL_USER: Xavier.T
      MYSQL_PASSWORD: xavier@Teoola_project

  apache-service:
    depends_on:
      - db
    container_name: apache-app
    image: httpd:latest
    cpus: 1.5
    mem_limit: 2048m
    ports:
      - "8000:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
    restart: always